set tabstop=4
set softtabstop=4
set expandtab
set number
set cursorline
filetype indent on
set wildmenu
set lazyredraw
set showmatch
set hlsearch  "highligh matches
set foldenable  "enable folding
let g:rehash256 = 1
